---
- secret:
    name: SECRET_OPENSTACK_HEALTH_MIDDLEWARE
    data:
      PYPI_API_TOKEN: !encrypted/pkcs1-oaep
        - RAh/PWu9Bp3nzIEl3G8nxPwY1CBuK0pifKAPJ0kgo+7CxFqLkvWSuAZ3gHtVZaOvK6Zbe
          ATxj23tKCeQYbtpI8pUlNONHLYSfZsqnZxGwcZDXZdzrls4jNRHYvfhlt+QZRQonho1ek
          X+Vq31mNg3I3EFbXbypF343KEz4apFPPFXDaBnuxU+wELSaMEYc+Bnxkr3yHHtsbDJ0hc
          sqXS7IcJW7PHpivyRZQE/xlrkOUPEnAgRinzNkGq4Y2SavSEAPIzQsY8YTw48O5XHdOqL
          0Wwqu+YYsnl68DC2a+KEcSEuH8JAweISlm2UTvbntbjyPcW86h6tEVJT2DYFpX8J7s75a
          RzGOChbPJ4C7/9szdPeO2dOmzxqNCTHZK1xsPEuBomkAy2EEewvUeVnqoGPDLNSHd11Xe
          erM0YnhCY7y9zdCu1oIXYEryC6b842+3ydPrJQvCLXsHcc0NM69CZ74opLrHH+disgnzw
          xMEQEXdrNw+cmWpUTxnTUOcMqeRneXFq+YC+de8k260KlmzwjfJiF5E+gLInmVuB8lBXE
          3GzdIK37v2OqDqu+v9H8P1oYV1X4coEPC9H5/6dgi9A9/npZeRLnpr8AdY+GRK4uYrGwf
          5LhUR0HVPQD1BOaS7w6YCSxzQnySDAKopjM59ZmbWpQNSRxS7bIIoi6DwKuf1A=

- job:
    name: openstack-health-middleware-publish-pypi-package
    parent: publish-pypi-package
    secrets:
      - name: secret
        secret: SECRET_OPENSTACK_HEALTH_MIDDLEWARE
        pass-to-parent: true
    vars:
      pypi_twine_executable: "/tmp/venv/bin/python -m twine"

- project:
    merge-mode: squash-merge
    default-branch: main
    check:
      jobs:
        - flake8
        - python-black
    gate:
      jobs:
        - flake8
        - python-black
    periodic-daily:
      jobs:
        - flake8
        - python-black
    tag:
      jobs:
        - openstack-health-middleware-publish-pypi-package
